# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9684ca4f21f70a0c93795a0ddbeb5404"
name = "happy-wishlist"
handle = "happy-wishlist"
application_url = "https://degree-review-argument-imperial.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://degree-review-argument-imperial.trycloudflare.com/auth/callback",
  "https://degree-review-argument-imperial.trycloudflare.com/auth/shopify/callback",
  "https://degree-review-argument-imperial.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
